
version: '3.3'
  
services:
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - portainer_data:/data
        deploy:
            labels:
               - "traefik.docker.network=traefik-net"
               - "traefik.port=9000"
               - "traefik.frontend.rule=HostRegexp:port{domain: \\.srv\\..+\\..+}"
        networks:
            - traefik-net
    traefik:
        image: traefik
        command: --api --docker --docker.swarmmode --docker.domain=sihle.locational.io --docker.watch
        ports:
            - "80:80"     # The HTTP port, not the web UI port
            - "8085:8080" # For debugging
            - "443:443"
        volumes:
            - ./acme.json:/acme.json
            - ./traefik.toml:/traefik.toml
            - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events
        deploy:
            labels:
               - "traefik.frontend.rule=HostRegexp:traefik{domain: \\.srv\\..+\\..+}"
               - "traefik.port=8080"
               - "traefik.docker.network=traefik-net"
            placement:
                constraints: [node.role == manager]
        networks:
           - traefik-net

networks:
    traefik-net:
       driver: overlay
       external: true
volumes:
    portainer_data:
