#debug = true
#logLevel = "ERROR"
#logLevel = "INFO"

[providers.docker] 
  endpoint = "unix:///var/run/docker.sock"
  swarmMode = true
  
[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myhttpchallenge.acme]
  email = "admin@peoplesized.com"
  storage = "/acme/certs.json"
  [certificatesResolvers.myhttpchallenge.acme.httpChallenge]
    # used during the challenge
    entryPoint = "web"

[api]
  dashboard = true

