[providers.docker]
  swarmMode = true
  useBindPortIP = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[http.middlewares]
  [http.middlewares.test-redirectscheme.redirectScheme]
    scheme = "https"

[api]
  dashboard = true